// Sample content seeded into an empty database. English-only by design (spec §10).

const FIG_Q6 = [
  '<svg viewBox="0 0 360 150" xmlns="http://www.w3.org/2000/svg" class="q-figure">',
  '<line x1="20" y1="120" x2="340" y2="120" stroke="#444" stroke-width="1.5"/>',
  '<line x1="30" y1="142" x2="30" y2="12" stroke="#444" stroke-width="1.5"/>',
  '<path d="M30 118 C 80 40, 150 30, 200 70 S 300 96, 340 58" fill="none" stroke="#2e6b31" stroke-width="2"/>',
  '<path d="M150 120 L150 42 C 168 38, 186 52, 200 70 L200 120 Z" fill="#9aa79a" opacity="0.45"/>',
  '<text x="143" y="136" font-size="12">π/6</text>',
  '<text x="194" y="136" font-size="12">π/3</text>',
  '<text x="16" y="136" font-size="12">O</text>',
  '<text x="330" y="112" font-size="12">x</text>',
  '<text x="38" y="24" font-size="12">y</text>',
  '</svg>',
].join('');

function q(subject, year, component, number, marks, topic, text, scheme, feedback, expected, figure) {
  return { subject, year, component, number, marks, topic, text, scheme, feedback, expected, figure: figure || null };
}

const questions = [
  // ---- Mathematics 2025 Component 2: full 12-question exam, 60 marks, expected sum 48 ----
  q('Mathematics', 2025, 2, 1, 3, 'Integration',
    'Find \\(\\int (x^{2} + 3x)\\,dx\\).',
    'M1 raise each power by one; A1 \\(\\frac{x^{3}}{3} + \\frac{3x^{2}}{2}\\); B1 constant of integration \\(+C\\).',
    'Good start! Remember that the integral of \\(x^{n}\\) is \\(\\frac{x^{n+1}}{n+1}\\). Also, do not forget the constant of integration.',
    3),
  q('Mathematics', 2025, 2, 2, 4, 'Differentiation',
    'Given \\(y = \\dfrac{x^{2}+1}{x-2}\\), find \\(\\dfrac{dy}{dx}\\) and determine the coordinates of the stationary points of the curve.',
    'M1 quotient rule; A1 \\(\\dfrac{x^{2}-4x-1}{(x-2)^{2}}\\); M1 set numerator to zero; A1 both stationary points.',
    'Your quotient rule setup is correct, but check the sign in the numerator — expand \\((x-2)(2x)\\) carefully before simplifying.',
    2),
  q('Mathematics', 2025, 2, 3, 2, 'Trigonometry',
    'Solve \\(2\\sin x - 1 = 0\\) for \\(0 \\le x \\le 2\\pi\\).',
    'B1 \\(x = \\frac{\\pi}{6}\\); B1 \\(x = \\frac{5\\pi}{6}\\).',
    'Correct method. Remember sine is positive in the first and second quadrants, so there are two solutions in the interval.',
    2),
  q('Mathematics', 2025, 2, 4, 5, 'Integration',
    'Use integration by parts to evaluate \\(\\int_{0}^{1} x e^{2x}\\,dx\\).',
    'M1 parts with \\(u = x\\); A1 \\(\\frac{x e^{2x}}{2} - \\int \\frac{e^{2x}}{2}\\,dx\\); A1 \\(\\frac{x e^{2x}}{2} - \\frac{e^{2x}}{4}\\); M1 apply limits; A1 \\(\\frac{e^{2}+1}{4}\\).',
    'Excellent work — the choice of \\(u\\) and \\(dv\\) is exactly right and the limits are applied correctly.',
    5),
  q('Mathematics', 2025, 2, 5, 3, 'Sequences and Series',
    'The third term of a geometric progression is 18 and the sixth term is 486. Find the first term and the common ratio.',
    'M1 divide terms to get \\(r^{3} = 27\\); A1 \\(r = 3\\); A1 \\(a = 2\\).',
    'You found the ratio equation but slipped when solving for \\(a\\) — substitute \\(r = 3\\) back into \\(ar^{2} = 18\\).',
    1),
  q('Mathematics', 2025, 2, 6, 5, 'Applications of Integration',
    'The diagram shows a sketch of the curve with equation \\(y = 2\\cos x + \\sec x\\). The shaded region, bounded by the curve, the \\(x\\)-axis, and the lines \\(x = \\frac{\\pi}{6}\\) and \\(x = \\frac{\\pi}{3}\\), is rotated about the \\(x\\)-axis. Find the exact volume of the solid generated.',
    'M1 \\(V = \\pi \\int y^{2}\\,dx\\); M1 expand \\((2\\cos x + \\sec x)^{2}\\); A1 \\(4\\cos^{2}x + 4 + \\sec^{2}x\\); M1 integrate each term; A1 exact volume.',
    'A strong attempt. When squaring \\(2\\cos x + \\sec x\\), remember the cross term \\(2 \\cdot 2\\cos x \\cdot \\sec x = 4\\), which integrates to \\(4x\\).',
    4, FIG_Q6),
  q('Mathematics', 2025, 2, 7, 6, 'Differentiation',
    'A closed cylindrical can has volume \\(250\\pi\\) cm\\(^{3}\\). Show that its surface area is \\(S = 2\\pi r^{2} + \\dfrac{500\\pi}{r}\\), and find the radius that minimises \\(S\\).',
    'B1 \\(h\\) in terms of \\(r\\); M1 substitute into \\(S\\); M1 \\(\\frac{dS}{dr} = 4\\pi r - \\frac{500\\pi}{r^{2}}\\); A1 set to zero; A1 \\(r = 5\\); B1 justify minimum.',
    'Nearly there — your derivative is right; justify the minimum with the second derivative test.',
    5),
  q('Mathematics', 2025, 2, 8, 4, 'Binomial Expansion',
    'Find the first four terms in the expansion of \\((1+2x)^{-3}\\) in ascending powers of \\(x\\), and state the range of values of \\(x\\) for which the expansion is valid.',
    'M1 binomial with \\(n = -3\\); A2 \\(1 - 6x + 24x^{2} - 80x^{3}\\); B1 valid for \\(|x| < \\frac{1}{2}\\).',
    'Great — all four terms and the validity condition are correct.',
    4),
  q('Mathematics', 2025, 2, 9, 5, 'Vectors',
    'The points \\(A(1, 2, 3)\\) and \\(B(4, 0, -1)\\) are given. Find \\(\\overrightarrow{AB}\\), \\(|\\overrightarrow{AB}|\\), and the unit vector in the direction of \\(\\overrightarrow{AB}\\).',
    'B1 \\(\\overrightarrow{AB} = (3, -2, -4)\\); M1 A1 \\(|\\overrightarrow{AB}| = \\sqrt{29}\\); M1 A1 unit vector.',
    'The vector and its magnitude are correct; the unit vector just needs each component divided by \\(\\sqrt{29}\\).',
    3),
  q('Mathematics', 2025, 2, 10, 7, 'Trigonometry',
    'Express \\(3\\sin\\theta + 4\\cos\\theta\\) in the form \\(R\\sin(\\theta + \\alpha)\\), where \\(R > 0\\) and \\(0 < \\alpha < 90^{\\circ}\\). Hence solve \\(3\\sin\\theta + 4\\cos\\theta = 2.5\\) for \\(0 \\le \\theta \\le 360^{\\circ}\\), and state the maximum value of the expression.',
    'B1 \\(R = 5\\); B1 \\(\\alpha = 53.1^{\\circ}\\); M1 \\(\\sin(\\theta + \\alpha) = 0.5\\); A2 both solutions; B1 maximum value 5; B1 method.',
    'Very good — \\(R\\) and \\(\\alpha\\) are right and one solution found; check the second solution using \\(180^{\\circ}\\) minus your principal value.',
    6),
  q('Mathematics', 2025, 2, 11, 6, 'Logarithms and Exponentials',
    'Solve the equation \\(3^{2x+1} = 5^{x+2}\\), giving your answer in exact logarithmic form and to 3 significant figures.',
    'M1 take logs of both sides; A1 \\((2x+1)\\ln 3 = (x+2)\\ln 5\\); M1 collect \\(x\\) terms; A1 exact form; A2 3 s.f. value.',
    'Correct log laws throughout — just double-check the 3 s.f. rounding at the end.',
    5),
  q('Mathematics', 2025, 2, 12, 10, 'Applications of Integration',
    'The curve \\(y = x^{2} - 4x + 5\\) and the line \\(y = 2x - 3\\) intersect at two points. (a) Find the coordinates of the points of intersection. (b) Find the exact area of the region enclosed between the curve and the line. (c) The region is rotated through \\(360^{\\circ}\\) about the \\(x\\)-axis. Write down, but do not evaluate, an integral expression for the volume generated.',
    '(a) M1 A1 \\(x = 2\\) and \\(x = 4\\); (b) M1 subtract functions; M1 integrate; A2 area \\(\\frac{4}{3}\\); (c) M1 A1 \\(\\pi\\int_{2}^{4}\\big((2x-3)^{2} - (x^{2}-4x+5)^{2}\\big)\\,dx\\); B2 presentation.',
    'A well-structured answer. Parts (a) and (b) are solid; in (c) make sure the outer function is the line, which lies above the curve on this interval.',
    8),

  // ---- Chemistry 2024 Component 1 (pool, 5 questions / 5 topics) ----
  q('Chemistry', 2024, 1, 1, 3, 'Atomic structure',
    'State the number of protons, neutrons and electrons in the ion \\(^{56}_{26}\\mathrm{Fe}^{3+}\\).',
    'B1 26 protons; B1 30 neutrons; B1 23 electrons.',
    'Careful with the electrons — a 3+ ion has lost three electrons relative to the atom.',
    2),
  q('Chemistry', 2024, 1, 2, 4, 'Electrolysis',
    'Molten lead(II) bromide is electrolysed using inert electrodes. Write the half-equations for the reactions at the cathode and the anode, and state one observation at each electrode.',
    'M1 A1 cathode \\(\\mathrm{Pb}^{2+} + 2e^{-} \\rightarrow \\mathrm{Pb}\\); M1 A1 anode \\(2\\mathrm{Br}^{-} \\rightarrow \\mathrm{Br}_{2} + 2e^{-}\\).',
    'Good half-equations. Remember oxidation happens at the anode — electrons appear on the right-hand side.',
    3),
  q('Chemistry', 2024, 1, 3, 4, 'Organic Chemistry',
    'Draw the displayed formula of but-2-ene and describe the test to distinguish it from butane, including the observation.',
    'B1 correct displayed formula; B1 bromine water; B1 alkene decolourises it; B1 butane gives no change.',
    'The bromine water test is right; make sure the double bond in your structure is between carbons 2 and 3.',
    3),
  q('Chemistry', 2024, 1, 4, 4, 'Chemical bonding',
    'Explain why sodium chloride has a high melting point and conducts electricity when molten but not when solid.',
    'B1 giant ionic lattice; B1 strong electrostatic forces; B1 ions free to move when molten; B1 ions fixed in solid.',
    'Clear explanation — link the conductivity to mobile ions, not electrons.',
    3),
  q('Chemistry', 2024, 1, 5, 5, 'Stoichiometry',
    'Calculate the mass of magnesium oxide formed when 6.0 g of magnesium burns completely in oxygen. \\((A_r:\\ \\mathrm{Mg} = 24,\\ \\mathrm{O} = 16)\\)',
    'M1 moles Mg = 0.25; M1 ratio 1:1; M1 A1 mass = 0.25 × 40; A1 10.0 g.',
    'Moles and ratio are correct — multiply by the molar mass of MgO (40), not of Mg.',
    4),

  // ---- Physics 2024 Component 1 (pool, 4 questions / 4 topics) ----
  q('Physics', 2024, 1, 1, 3, 'Kinematics',
    'A car accelerates uniformly from rest to \\(24\\ \\mathrm{m\\,s^{-1}}\\) in 8.0 s. Calculate the acceleration and the distance travelled.',
    'M1 A1 \\(a = 3.0\\ \\mathrm{m\\,s^{-2}}\\); M1 A1 \\(s = 96\\ \\mathrm{m}\\).',
    'Acceleration is right; for the distance use \\(s = \\frac{1}{2}(u+v)t\\).',
    2),
  q('Physics', 2024, 1, 2, 4, 'Electricity',
    'A 12 V battery drives a current of 0.50 A through a resistor for 2.0 minutes. Calculate the resistance and the energy transferred.',
    'M1 A1 \\(R = 24\\ \\Omega\\); M1 A1 \\(E = 720\\ \\mathrm{J}\\).',
    'R is correct. For the energy, remember to convert minutes to seconds before using \\(E = VIt\\).',
    3),
  q('Physics', 2024, 1, 3, 4, 'Waves',
    'A wave has frequency 250 Hz and wavelength 1.32 m. Calculate the wave speed, and state what happens to the wavelength if the frequency doubles while the speed stays constant.',
    'M1 A1 \\(v = 330\\ \\mathrm{m\\,s^{-1}}\\); B1 wavelength halves; B1 reasoning.',
    'Good — speed correct and the inverse relationship clearly stated.',
    4),
  q('Physics', 2024, 1, 4, 5, 'Forces and Motion',
    'A 2.0 kg block is pulled along a horizontal surface by a 12 N force against a friction force of 4.0 N. Calculate the acceleration of the block, and its speed after 3.0 s starting from rest.',
    'M1 resultant force 8.0 N; M1 A1 \\(a = 4.0\\ \\mathrm{m\\,s^{-2}}\\); M1 A1 \\(v = 12\\ \\mathrm{m\\,s^{-1}}\\).',
    'Resultant force handled well; remember to subtract friction before applying \\(F = ma\\).',
    4),

  // ---- Biology 2024 Component 1 (pool, 4 questions / 4 topics) ----
  q('Biology', 2024, 1, 1, 3, 'Cell Biology',
    'Describe two differences between plant and animal cells, and name the organelle responsible for photosynthesis.',
    'B1 B1 two differences; B1 chloroplast.',
    'Two clear differences given — also name the chloroplast explicitly for the final mark.',
    2),
  q('Biology', 2024, 1, 2, 4, 'Genetics',
    'In pea plants, tall (T) is dominant over short (t). Two heterozygous plants are crossed. Draw the Punnett square and state the expected phenotype ratio of the offspring.',
    'M1 correct gametes; A1 square; A1 3:1 tall to short; B1 genotype ratio 1:2:1.',
    'The Punnett square is correct — state the ratio as phenotypes (3 tall : 1 short).',
    3),
  q('Biology', 2024, 1, 3, 4, 'Ecology',
    'Explain what is meant by a food web, and describe what could happen to a population of secondary consumers if the producers were removed.',
    'B1 definition; M1 A1 knock-on effects through trophic levels; B1 population falls.',
    'Good chain of reasoning through the trophic levels.',
    4),
  q('Biology', 2024, 1, 4, 5, 'Human Physiology',
    'Describe the pathway of blood through the heart, starting from the vena cava, and explain the role of the valves.',
    'B2 correct pathway; B2 valves prevent backflow; B1 terminology.',
    'Pathway mostly right — remember blood passes through the lungs between the right and left sides of the heart.',
    3),
];

module.exports = { questions };
